### ISSUE TITLE
serialization not included in maven jars for neoforge since version 5.2

### ISSUE THREAD

**Issue by ghostflyby** [thedarkcolour/KotlinForForge#102]
as in https://github.com/thedarkcolour/KotlinForForge/tree/site/thedarkcolour/kotlinforforge-neoforge/5.2.0
<img width="810" alt="k" src="https://github.com/thedarkcolour/KotlinForForge/assets/57822596/5e981257-08c7-4ca2-95a9-994c741d62f4">

**Comment by thedarkcolour** [comment]
https://github.com/neoforged/NeoGradle/issues/222

**Comment by thedarkcolour** [comment]
Fixed. You may need to set changing = true on your Kotlin dependency to get the updated Maven artifact.
