### ISSUE TITLE
[Question] How are you supposed to use SubscribeEvent in non-mod classes?

### ISSUE THREAD

**Issue by filloax** [thedarkcolour/KotlinForForge#107]
For instance, let's say I have a `ModNetworking` class where I want to subscribe to the `RegisterPayloadHandlersEvent' statically, as the class is instanced elsewhere (example: ServiceLoader) so I cannot make it an object.
Do I place @EventBusSubscriber on the class, and @SubscribeEvent on a @JvmStatic method in the companion object?

**Comment by thedarkcolour** [comment]
Here's the correct usage:
```kotlin
class Test {
    // other methods...

    @EventBusSubscriber(bus=EventBusSubscriber.Bus.MOD)
    companion object {
        @SubscribeEvent
        fun onGameStart(event: FMLCommonSetupEvent) {
            println("Test print please ignore")
        }
    }
}
```

KFF treats the companion object the same as any other `object` declaration, so all you need to do is annotate the companion object. No need to use @JvmStatic, KFF will use the object instance.
