### ISSUE TITLE
[1.21.2 - 1.21.3] Support on CurseForge / Modrinth

### ISSUE THREAD

**Issue by ghost** [thedarkcolour/KotlinForForge#109]
As far as I'm aware there's no compile errors in the codebase when targeting 1.21.3 and there is no issue at least in combination with my mod Expanded Storage running it in production on NeoForge. 

Would it be possible to have the mod marked as compatible for the newer Minecraft versions please.

Many Thanks - Quinn

**Comment by thedarkcolour** [comment]
Done
