### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.has(String)" because "jsonObject" is null 	at toughasnails.util.serialization.ItemStackDeserializer.deserialize(ItemStackDeserializer.java:24) ~[ToughAsNails-forge-1.20.1-9.2.0.171.jar%23312!/:9.2.0.171] {re:classloading}

### ISSUE THREAD

**Issue by Beata-Scheisner-Petersen** [thedarkcolour/KotlinForForge#111]
Kotlin for Forge 4.11.0 and Tough As Nails Forge 1.20.1 - 9.2.0.171 crashes then put in same pack. Is there anything I can do to make it work?

[crash-2024-12-05_15.37.31-client.txt](https://github.com/user-attachments/files/18024895/crash-2024-12-05_15.37.31-client.txt)

[latest.log](https://github.com/user-attachments/files/18024907/latest.log)

**Comment by TheMCSpacePro** [comment]
How did you fix it?
