### ISSUE TITLE
version in mods.toml not updated to 1.7.0

### ISSUE THREAD

**Issue by exzhawk** [thedarkcolour/KotlinForForge#12]
Did you forget mods.toml when bumping version to 1.7.0 in 668b5c35ea900750c35f2ea8d878c1c5e6a04607 ?
https://github.com/thedarkcolour/KotlinForForge/blob/668b5c35ea900750c35f2ea8d878c1c5e6a04607/src/main/resources/META-INF/mods.toml#L33

**Comment by thedarkcolour** [comment]
I did, thanks for catching that
