### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Capones429** [thedarkcolour/KotlinForForge#15]
when ever I load up the forge client with the kotlineforforge in the mod folder it starts to crash, as well as when i remove the adorn mod from the folder

**Comment by thedarkcolour** [comment]
Crash log?

**Comment by Capones429** [comment]
wheres that

**Comment by thedarkcolour** [comment]
Go to .minecraft/logs and get the lastest.log

**Comment by thedarkcolour** [comment]
Uhhhh Adorn is a Fabric mod not a Forge mod

**Comment by Capones429** [comment]
its is? but there a forge verison
also when i remove it from the folder it crashes the game

**Comment by Capones429** [comment]
[debug-5.log.gz](https://github.com/thedarkcolour/KotlinForForge/files/5991204/debug-5.log.gz)

**Comment by thedarkcolour** [comment]
It's a bug in Oh The Biomes You'll Go

**Comment by thedarkcolour** [comment]
And maybe Charm as well

**Comment by Capones429** [comment]
what do you mean?

**Comment by Capones429** [comment]
ok so its just that charm doesn't work, maybe its because i have quark as well but thank you non the less
