### ISSUE TITLE
Error entering the world for the second time

### ISSUE THREAD

**Issue by kellixon** [thedarkcolour/KotlinForForge#16]
MC 1.16.5. Forge 36.1.0(3). 262 mods +- Kotlin. All default settings.
Without Kotlin, I create a world and go to it as many times as I want. With Kotlin, I create a world and can't log in later times.
Bad log with Kotlin (I can't log in to world a second time) - https://gist.github.com/kellixon/eac7f1f30970e1803acda3c0f1834143
Good log without Kotlin - https://gist.github.com/kellixon/ea8dd25060e8a951af13531521e5767b
My localpack (zip, only mods) - https://yadi.sk/d/ShAh2B5-_AfBNQ

**Comment by thedarkcolour** [comment]
What mods depend on Kotlin in your modpack?

**Comment by kellixon** [comment]
Bountiful, but I temporarily removed it, only with Kotlin

**Comment by thedarkcolour** [comment]
It looks like the bad log doesn't have Kotlin but the good log does have Kotlin?

**Comment by thedarkcolour** [comment]
Seems like a structure error with one of the mods

**Comment by kellixon** [comment]
Yes, I mixed up the logs in places

**Comment by thedarkcolour** [comment]
I'm getting a different error than you, but I can't test any further because my computer can't handle the modpack

**Comment by kellixon** [comment]
Yes, it would be great, but only if you are not difficult and have time! 
ps. I allocate 12Gb of RAM for the build.

**Comment by thedarkcolour** [comment]
Nobody's testing this and it's probably an issue with another mod that depends on KFF, so I'm going to close the issue
