### ISSUE TITLE
Missing class for kotlinx

### ISSUE THREAD

**Issue by Windmill-City** [thedarkcolour/KotlinForForge#17]
[https://github.com/Windmill-City/IngameIME-Minecraft/issues/4](url)
java.lang.NoClassDefFoundError: kotlinx/coroutines/GlobalScope
Using kotlinforforge-1.11.0
Compared 1.11.0 to 1.10.0, I found the latest version missing some class in kotlinx package

**Comment by thedarkcolour** [comment]
Hmm, I guess that was why the jar size was smaller :/

**Comment by thedarkcolour** [comment]
Try with 1.11.1?

**Comment by Windmill-City** [comment]
It works well now
