### ISSUE TITLE
Suggestion: Consider a more permissive license than GPL-3.0

### ISSUE THREAD

**Issue by klikli-dev** [thedarkcolour/KotlinForForge#19]
I would like to bring up, once again, the discussion from #5, especially my ( I believe ) unnoticed reply https://github.com/thedarkcolour/KotlinForForge/issues/5#issuecomment-764461698 

My suggestion is to use a permissive license, such as LGPL 2.1/3 or even MIT/Apache/BSD/... in order to give modders the freedom to choose their own license for their creations if they use your library.

Why do I make this suggestion? Well, personally I like to license my mods under very permissive licenses such as the MIT, in order to allow people to freely use it for their projects, without having to worry about licenses too much. At the same time I'd like to use your work in a future project, to make my own life easier, but without restricting the freedom of those that want to base their works on my (future) work :) 

Currently your library is under GPL-3.0, which means that anyone who wants to use it needs to license their own mod under GPL-3.0 as well, they **cannot** choose their own license. Compared to that forge uses the more liberal LGPL, that allows modders to choose a license for their own work freely.

Based on your reply https://github.com/thedarkcolour/KotlinForForge/issues/5#issuecomment-698544319 I believe you actually want the same thing that forge wants: Giving modders freedom, which in turn allows more people to use your library compliantly.

If that is not the case and you chose GPL-3.0 deliberately to make sure people share their own mods under the GPL-3.0, then please ignore this issue. 

Finally, thank you for the great work you did with this library, and if I can help clear up any licensing questions feel free to ask!

**Comment by thedarkcolour** [comment]
Alright sounds good
