### ISSUE TITLE
Available for <1.13

### ISSUE THREAD

**Issue by snowe2010** [thedarkcolour/KotlinForForge#2]
I'm super new to minecraft modding, so please forgive me if the answer to this is obvious, but is it possible to use this with the old `mcmod.info` style?

**Comment by thedarkcolour** [comment]
It is not. If you wanted to use Kotlin for 1.12.2, use Shadowfacts' Forgelin. For 1.13+, you would use a mods.toml. There's one that comes with the example mod from the MDK, so I would check that out.
