### ISSUE TITLE
Not working on server

### ISSUE THREAD

**Issue by Tubelex** [thedarkcolour/KotlinForForge#23]
So I looked at past issues and was able to fix all the issues from the client side but on the server side KotlinForForge doesn't seem to work (mod language) for better foliage. Here is the log (all the other issues are fine, it's just the final lines, Better Foliage, that crash the server):
https://mclo.gs/SABovyS
- that's the link to take you to the log

**Comment by thedarkcolour** [comment]
Why would you use better foliage on the server
And why wouldn't you report it to their github?

**Comment by thedarkcolour** [comment]
Pretty sure Better Foliage is a client side mod, and if this isn't intended behavior report it to them

**Comment by Tubelex** [comment]
alright, thanks
