### ISSUE TITLE
[Idea] Make file subscibeable

### ISSUE THREAD

**Issue by GoogeTan** [thedarkcolour/KotlinForForge#26]
We can subscribe classes and objects but can not subscribe files. Let's fix it!

**Comment by Username404-59** [comment]
That would be nice

**Comment by thedarkcolour** [comment]
Would this be with an annotation?

**Comment by Username404-59** [comment]
Yes, you could use it like @file:Subscribe

**Comment by thedarkcolour** [comment]
forgot to close this but added in 1.13.0

**Comment by Username404-59** [comment]
Wasn't it 1.12.2?

**Comment by thedarkcolour** [comment]
Ah you're right
