### ISSUE TITLE
1.16.5 Issue with Kotlin and Titanium. 

### ISSUE THREAD

**Issue by Runburner** [thedarkcolour/KotlinForForge#28]
I recently was updating mods in my pack and kept running into a clientside crash on startup pointing fingers at Titanium. However, as I tried reading what I could of the errors to see what was being called, I noticed Kotlin and the mods that used it were being called up, I reverted from Kotlin 1.15.0-obf to 1.14.0-obf and the issue cleared up. 

Here is a Pastebin with the logs from the console from startup to crash. https://pastebin.com/nqBQY7mh
Please let me know if this is an issue here or if I should create an issue over on the Titanium mod. My assumption is that it's Kotlin possibly due to the fact that I rolled back Kotlin and it worked but it didn't work if I tried rolling back the Titanium update. 

The two Titanium versions I was using by the way are
Old: Titanium 1.16.5| 3.2.8.5-19
Newer: Titanium 1.16.5| 3.2.8.5-20

**Comment by thedarkcolour** [comment]
I'll look into it, just archived the file on curse

**Comment by thedarkcolour** [comment]
1.15.1 should work fine

**Comment by Runburner** [comment]
My dude that was the fastest patch and response I've ever seen. Updated to 1.15.1 and was able to launch and get in-game! Thank you very much!
