### ISSUE TITLE
FMLClientSetupEvent doesn't seem to trigger with FORGE_BUS

### ISSUE THREAD

**Issue by SamiSaves** [thedarkcolour/KotlinForForge#3]
Hey,

I am trying to create a custom entity and what I've gathered is that most mods register the renderers from `FMLClientSetupEvent` using `RenderingRegistry.registerEntityRenderingHandler`. I tried using the `FORGE_BUS` and passing it a function that takes `FMLClientSetupEvent` as a parameter, but this method never triggeres.

Here is a shortened version onf my main class. Right now I am just trying to get the onClientSetup method to trigger.

```kt
object Main {
	val logger: Logger = LogManager.getLogger()

	init {
		FORGE_BUS.addListener(::setupClient)
	}

	private fun setupClient(event: FMLClientSetupEvent) {
		logger.log(Level.INFO, "Client setup called!")
	}
}
```

So my question is that how can I trigger this event, and if I can't do you have any suggestions where I could register my entity renders for the client side?

**Comment by thedarkcolour** [comment]
`FMLClientSetupEvent` is fired on the `MOD_BUS`, not the `FORGE_BUS`.

**Comment by SamiSaves** [comment]
Yeah that works, thanks!

Can I do a pr and add it to the example repository? As far as I know it is very often used in modding so it might be helpful to have it there as an example. The `FMLServerAboutToStartEvent` there threw me off badly in this case.

**Comment by thedarkcolour** [comment]
I found that typo. It'll be fixed in next KFF.
