### ISSUE TITLE
[1.x] Compatibility Issue Between Sponge and Kotlin

### ISSUE THREAD

**Issue by uwuscutely** [thedarkcolour/KotlinForForge#34]
Server crashes on startup https://bin.bloom.host/dexeremiwa.rb

Sponge states that needed changes were made for 1.17+. Wondering if those changes can be ported to 1.16 as well.

Link to Sponge issue: https://github.com/SpongePowered/Sponge/issues/3642

**Comment by thedarkcolour** [comment]
Could you send a list of other 1.16 mods that use Kotlin for Forge? I wanna test a fix to the issue

**Comment by uwuscutely** [comment]
The only other mod I'm aware of which uses Kotlin for Forge in 1.16 is BetterFoliage. However, that's a client side only mod
https://www.curseforge.com/minecraft/mc-mods/better-foliage

**Comment by uwuscutely** [comment]
https://www.curseforge.com/minecraft/mc-mods/adorn-for-forge
https://www.curseforge.com/minecraft/mc-mods/bamboo-tweaks-forge
https://www.curseforge.com/minecraft/mc-mods/grapple-hooks
https://www.curseforge.com/minecraft/mc-mods/hardcore-dungeons
https://www.curseforge.com/minecraft/mc-mods/industrial-expansion-te-addon
https://www.curseforge.com/minecraft/mc-mods/moar-boats
https://www.curseforge.com/minecraft/mc-mods/chickensshed

Had another look around and realized I could filter all the mods using Kotlin for Forge as dependents. Here's ones in 1.16 or support 1.16

**Comment by thedarkcolour** [comment]
[kotlinforforge-1.17.0-obf.zip](https://github.com/thedarkcolour/KotlinForForge/files/8175501/kotlinforforge-1.17.0-obf.zip)
Does this Jar fix the issue? I couldn't figure out how to install SpongeForge
The jar is inside the zip file

**Comment by uwuscutely** [comment]
I'll load it up and see when I get a chance. To install [SpongeForge](https://www.spongepowered.org/downloads/spongeforge?minecraft=1.16.5&offset=0), all you have to do is put the SpongeForge JAR in the mods folder and load it up like a normal Forge server

**Comment by uwuscutely** [comment]
It seems to have crashed again with the new version as well https://bin.bloom.host/ayivuyejax

**Comment by thedarkcolour** [comment]
Update to KFF 1.17.0
