### ISSUE TITLE
(1.18.x) Any chance at rebundling JetBrains annotations?

### ISSUE THREAD

**Issue by ghost** [thedarkcolour/KotlinForForge#39]
Getting a crash in prod as Forge 1.18 doesn't *actually* bundle annotations, it only makes it available at compile time, not runtime.

If necessary, [here's a crash report with said crash](https://hst.sh/eyugixobez.md), thank you.

**Comment by thedarkcolour** [comment]
Alright

**Comment by thedarkcolour** [comment]
JetBrains annotations is bundled in 3.3.2 now 👍
