### ISSUE TITLE
Exception registering block with KDeferredRegister

### ISSUE THREAD

**Issue by michele-grifa** [thedarkcolour/KotlinForForge#4]
Hi,
i downloaded the new 1.4.0 version of the library and in the SkeletonRepository i noticed the **KDeferredRegister** use, but when i try to convert my existing blocks to delegates, it show me the error:

**kotlin.UninitializedPropertyAccessException: lateinit property value has not been initialized**

From what I understand, the slab that refers to the planks, is initialized before the planks themselves.
The library don't register automatically the planks blocks the first time i request it?

Thanks

```
val blocks = KDeferredRegister(ForgeRegistries.BLOCKS, MoreStuffMod.MODID)

    val japCherryPlanks by blocks.register("jap_cherry_planks") {
        Block(AbstractBlock.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD))
    }

val japCherrySlab by blocks.register("jap_cherry_slab") { SlabBlock(AbstractBlock.Properties.from(japCherryPlanks)) }
```

**Comment by thedarkcolour** [comment]
I'll look into it

**Comment by thedarkcolour** [comment]
Found the issue, I was using the wrong Map

**Comment by michele-grifa** [comment]
When I can get the new version? Or I have to compile myself?

**Comment by thedarkcolour** [comment]
I just put it out. It should show up in the maven repo.

**Comment by thedarkcolour** [comment]
CurseForge is still approving it

**Comment by michele-grifa** [comment]
Thanks
