### ISSUE TITLE
Missing versions on Modrinth

### ISSUE THREAD

**Issue by bloxgate** [thedarkcolour/KotlinForForge#41]
Is there any chance we can see some of the more recent versions on Modrinth? The latest available from there seems to only be v3.1.0

**Comment by thedarkcolour** [comment]
Modrinth had some issues before with language loader jars not having a mods.toml file, but it seems like they've resolved it now.

**Comment by thedarkcolour** [comment]
I still get issues for the 1.17 version. v3.5.0 is up though

**Comment by thedarkcolour** [comment]
I will upload neither the old 1.17 versions nor the old 1.18+ versions, but all new releases will be uploaded, let me know if you specifically require an old 1.17/1.18 version
