### ISSUE TITLE
HorizontalDirectionalBlock.FACING is null

### ISSUE THREAD

**Issue by Sunbread** [thedarkcolour/KotlinForForge#42]
I don't know where I went wrong, but when I try loading a block with BlockState HorizontalDirectionalBlock.FACING, the game crashes and tells me "Cannot invoke "net.minecraft.world.level.block.state.properties.Property.getName()" because "pProperty" is null".
The KFF version is 3.6.0. Using parchment mappings.

**Comment by Sunbread** [comment]
same as "BlockStateProperties.HORIZONTAL_FACING"

**Comment by Sunbread** [comment]
I figured out. The BlockState is static so the impl in Kotlin must be in the companion object

**Comment by Sunbread** [comment]
> I figured out. The BlockState is static so the impl in Kotlin must be in the companion object

I suggest BlockState shoule be added in examples

**Comment by thedarkcolour** [comment]
I'm a little confused... could you send a snippet of what caused this crash? I think Java's static to Kotlin's companion objects is fairly straightforward
