### ISSUE TITLE
Game crashes on start-up

### ISSUE THREAD

**Issue by Nevrai** [thedarkcolour/KotlinForForge#47]
My game crashes immediately on start-up. I narrowed it down to Kotlin for Forge. Disabling Kotlin for Forge lets the game boot normally, aside from not booting because of the mods that require Kotlin for Forge.

    Exception in thread "main" 
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

No crash report is generated, and I couldn’t find anything relevant in the log.

**latest.log** = https://pastebin.com/raw/EX551YSc

**Console errors:** https://pastebin.com/raw/UpFTZ0tb

### Versions
* **Minecraft:** 1.18.2
* **Forge:** 40.1.80 (latest for 1.18.2)
* **Kotlin for Forge:** 3.7.1 (latest for 1.18.2)

**Comment by thedarkcolour** [comment]
Not a Kotlin for Forge issue. Anti Ad mods mixins dont work properly, complain to them.

**Comment by Nevrai** [comment]
@thedarkcolour What do you mean “Anti Ad mod”? Are you talking about [No Telemetry](https://www.curseforge.com/minecraft/mc-mods/no-telemetry)? My game did launch fine without Kotlin for Forge.

**Comment by thedarkcolour** [comment]
The issue comes from a mod whose code is in "org.anti_ad.mc.common.config.options.ConfigBoolean"

**Comment by thedarkcolour** [comment]
Which mods depend on Kotlin for Forge? Have you tried removing those along with Kotlin for Forge?

**Comment by Peli93ESP** [comment]
entonces no hay solucion no?

**Comment by Peli93ESP** [comment]
porque ami me pasa exactamente lo mismo que al compañero de arriba

**Comment by thedarkcolour** [comment]
Un de los mods tiene un error que causa el juego a cerrar, y porque no lo esta de kff cierre este issue

**Comment by Peli93ESP** [comment]
pero InventoryProfilesNext le hace falta este mod, entonces no pode utilizar el InventoryProfilesNext

**Comment by thedarkcolour** [comment]
Es el problema de InventoryProfilesNext y se necesita reportado a su GitHub, porque es un error de su codigo, no de mio.

**Comment by Peli93ESP** [comment]
lo raro es que hace unos dias si funcionaba y ahora no
