### ISSUE TITLE
KotlinForForge disables minecraftLibrary configuration

### ISSUE THREAD

**Issue by switefaster** [thedarkcolour/KotlinForForge#50]
The `minecraftLibrary` dependency configuration and [kff-3.7.1.gradle](https://raw.githubusercontent.com/thedarkcolour/KotlinForForge/site/thedarkcolour/kotlinforforge/gradle/kff-3.7.1.gradle) both employ lazyToken to append files to runs' classpath. However, lazyToken takes only one supplier. Thus in practice, one will always take over another's result(in my case, my dependencies are overwritten by kotlin runtimes in the classpath file). Is there any way to solve this?

**Comment by thedarkcolour** [comment]
I don't have a great solution for you, but this works for me:
![image](https://user-images.githubusercontent.com/30441001/203835345-19c0cac8-609a-4cce-9b7d-bd426b756ac8.png)

**Comment by thedarkcolour** [comment]
I get the following in my runClient_minecraftClasspath.txt
![image](https://user-images.githubusercontent.com/30441001/203835595-d2a397bd-f6ec-44e9-9706-29b8121528c2.png)

**Comment by thedarkcolour** [comment]
Use `File.pathSeparator` instead of semicolons though, since semicolons work only for Windows systems

**Comment by switefaster** [comment]
Thanks for your solution! Additionally, following code automates the process
```groovy
minecraft.runs.all {
    String previous = lazyTokens['minecraft_classpath'].get()
    lazyToken('minecraft_classpath') {
        configurations.minecraftLibrary.copyRecursive().resolve().collect {
            it.absolutePath
        }.join(File.pathSeparator) + File.pathSeparator + previous
    }
}
```
But we need to patch [kff-3.7.1.gradle](https://raw.githubusercontent.com/thedarkcolour/KotlinForForge/site/thedarkcolour/kotlinforforge/gradle/kff-3.7.1.gradle) somehow to make it work
```groovy
repositories {
    // THIS LINE ADDED
    mavenCentral()
    maven {
        name = 'Kotlin for Forge'
        url = 'https://thedarkcolour.github.io/KotlinForForge/'
    }
}
```
