### ISSUE TITLE
KotlinForForge 3.9.0+ does not contain classes from org.jetbrains:annotations

### ISSUE THREAD

**Issue by DJtheRedstoner** [thedarkcolour/KotlinForForge#53]
`org.jetbrains:annotations` is a dependency of `kotlin-stdlib` and was contained in previous versions of KotlinForForge. This is a critical regression for mods that depended on these classes being present at runtime.

**Comment by thedarkcolour** [comment]
Fixed in 3.9.2

**Comment by thedarkcolour** [comment]
May I ask why you need compile-time annotations available at runtime?

**Comment by DJtheRedstoner** [comment]
They are used as part of our custom command system (which uses reflection at runtime to find handlers) to indicate optional arguments. However looking at it now, jetbrains annotations use `RetentionPolicy.CLASS` so our system may not actually work as intended. I will investigate further.

Edit: Yep, our system is broken.

**Comment by thedarkcolour** [comment]
I'm not going to bundle them anymore since they're useless at runtime.
