### ISSUE TITLE
[1.19.2] Startup crash with Croptopia - org.jetbrains.annotations

### ISSUE THREAD

**Issue by Peca21** [thedarkcolour/KotlinForForge#54]
When I place Kotlin for forge and croptopia in the same modpack game crashes immediately on startup.

Log: https://paste.ee/p/mMjgl

**Comment by Peca21** [comment]
https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues/487

**Comment by thedarkcolour** [comment]
Using Kotlin for Forge 3.9.1 should let you run the game.

**Comment by agentwolf88** [comment]
Same

**Comment by thedarkcolour** [comment]
I removed 3.9.2 from CurseForge and Modrinth. 
If you have errors with Essential mod on world load or opening world
`Internal Exception: java.lang.NoClassDefFoundError: org/jetbrains/annotations/Nullable`
use [Kotlin for Forge 3.8.0](https://modrinth.com/mod/kotlin-for-forge/version/3.9.1).

**Comment by starixed** [comment]
still keeps crashing, ive resulted on not updating croptopia

**Comment by thedarkcolour** [comment]
Which version of KFF/Minecraft are you using?

**Comment by starixed** [comment]
minecraft 1.19.2
ive used KFF 3.8.0, and 3.7.1

sometimes it seems to load but cannot enter world

**Comment by thedarkcolour** [comment]
Does 3.9.1 work for you?

**Comment by starixed** [comment]
3.9.1 does work however it will not let me enter any worlds, even new ones

**Comment by thedarkcolour** [comment]
Are you using Essential?

**Comment by starixed** [comment]
i do not have "Essential" unless you mean like ftb essentials or inventory essentials

**Comment by thedarkcolour** [comment]
Can you send the log for when you try to enter a new world but can't? @starixed

**Comment by starixed** [comment]
@thedarkcolour  sure. i was able to join just fine after a force crash this morning but later now that im home its not letting me join the world now
[latest.log](https://github.com/thedarkcolour/KotlinForForge/files/10377202/latest.log)
[debug.log](https://github.com/thedarkcolour/KotlinForForge/files/10377203/debug.log)
actually i just remember i disabled croptopia so i could play.
Update:: nothing seems to working now

**Comment by thedarkcolour** [comment]
Check if the croptopia is working now? They fixed the incompatibility of Peca's issue

**Comment by starixed** [comment]
i see no update for 1.19.2 forge only for 1.19.3 fabric

**Comment by thedarkcolour** [comment]
Weird, wonder why they closed the issue then https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues/487

**Comment by starixed** [comment]
idk, ill just wait patiently then.

Tomorrow he will post a build. so until then

**Comment by starixed** [comment]
new build tested and still cant join any world. idk what else it could be. 
[debug.log](https://github.com/thedarkcolour/KotlinForForge/files/10397964/debug.log)
[latest.log](https://github.com/thedarkcolour/KotlinForForge/files/10397966/latest.log)

**Comment by thedarkcolour** [comment]
This does not seem like a Kotlin for Forge problem. Have you tried without Croptopia/KFF ?

**Comment by starixed** [comment]
yeah i just created a new world and was able to join it. so it seems my old world is corrupted. im gonna test my backups so i dont lose too much. thanks for your help
