### ISSUE TITLE
Including language provider in a mod jar file?

### ISSUE THREAD

**Issue by chimbersaw** [thedarkcolour/KotlinForForge#58]
Hi! I am very new to minecraft modding and am now trying to figure out a way to load my mod as a single jar.
I've learned that you can use `jarjar` or shadow jar for mod dependencies but it doesn't seem to work for a language provider such as yours.
Could be please explain me if there is a way to include your jar in a mod so that a user doesn't have to manually download it and place it in the mods folder?
What is the preferred method of doing so?

**Comment by thedarkcolour** [comment]
This is not currently possible due to a [limitation in Forge](https://github.com/MinecraftForge/MinecraftForge/issues/8878#issuecomment-1381070386).

**Comment by chimbersaw** [comment]
thx for clarifying
