### ISSUE TITLE
"Fired/firing event for modid ..." messages in console are annoyingly verbose

### ISSUE THREAD

**Issue by ThePuzzlemaker** [thedarkcolour/KotlinForForge#62]
https://github.com/thedarkcolour/KotlinForForge/blob/a3aafbb71095de3036a66fe9d8c7738334ff6a33/kfflang/src/main/kotlin/thedarkcolour/kotlinforforge/KotlinModContainer.kt#L99-L101

I don't exactly understand why these messages are here, and why they're not toggleable (without disabling all other debug messages, or doing some fancy log4j2 filtering). Wouldn't it *at least* be sensible to make them trace rather than debug?

**Comment by thedarkcolour** [comment]
You're right, it should be in trace. Used to be debug in older versions and I never changed it.
