### ISSUE TITLE
Description Typo "kotiln"

### ISSUE THREAD

**Issue by Command17** [thedarkcolour/KotlinForForge#64]
There is a little typo in the description of the mod (mod.toml)

Instead of "Makes _**kotlin**_ forge-friendly" there is "Makes _**kotiln**_ forge-friendly"

**Comment by thedarkcolour** [comment]
Haha of course...

**Comment by thedarkcolour** [comment]
I'll fix it now for 4.x since I'm going to update it right now, but it will have to wait for 3.x.

**Comment by Shubhamraut01** [comment]
assign this to me

**Comment by thedarkcolour** [comment]
no
