### ISSUE TITLE
Crashes minecraft

### ISSUE THREAD

**Issue by AstroJoot** [thedarkcolour/KotlinForForge#67]
Whenever I launch Minecraft with it in my mod list it crashes and I have no clue why, exit code is: 1

**Comment by thedarkcolour** [comment]
Visit the Discord server of whatever mod you are using that requires KFF (Cobblemon? Better Foliage? InvProfiles Next?)

**Comment by AstroJoot** [comment]
But it's only KFF because I went through all my mods and it only stopped crashing when i disabled KFF

**Comment by thedarkcolour** [comment]
I assure you it's not (it has never been in dozens of reports), it's whatever mod you're using that depends on KFF
