### ISSUE TITLE
FIX IT FOR 1.19.2

### ISSUE THREAD

**Issue by lickmyasz** [thedarkcolour/KotlinForForge#69]
Trying to use this mod at all just crashes the game error code 1 just so you know
![Screenshot from 2023-04-23 17-39-41](https://user-images.githubusercontent.com/131621966/233867655-9cadd234-fc27-4293-bb14-ceb5edc28c04.png)

**Comment by thedarkcolour** [comment]
Don't use all caps lol. Could you send something more helpful, a log perhaps?

**Comment by maltadutch** [comment]
[2023-04-24-1.log.gz](https://github.com/thedarkcolour/KotlinForForge/files/11313564/2023-04-24-1.log.gz)

**Comment by maltadutch** [comment]
i had the same problem, here is the log. the mod I am trying to play is cobblemon

**Comment by thedarkcolour** [comment]
You guys don't even have Kotlin for Forge installed
What version of KFF are you using? Send mods folder screenshot?

**Comment by thedarkcolour** [comment]
I'm gonna close this if there isn't any more information. @lickmyasz ?

**Comment by lickmyasz** [comment]
It was not your mod or coblemon's falt it was the falt of the person who
made the modpack I was trying to use and made then posted it to curseforge
without bothering to see if it worked.
