### ISSUE TITLE
1.20 Release

### ISSUE THREAD

**Issue by ejektaflex** [thedarkcolour/KotlinForForge#72]
Hi! Minecraft 1.20 is out, and as such Kotlin mods for Forge (usually) depend on this. Just putting it on your radar 😃

**Comment by YuRaNnNzZZ** [comment]
4.2.0 release functions in 1.20 just fine, only version range needs to be changed in kffmod

**Comment by ejektaflex** [comment]
> 4.2.0 release functions in 1.20 just fine, only version range needs to be changed in kffmod

Im sure it does, but I can't do that for a Maven dependency or ask users to do that :)

**Comment by thedarkcolour** [comment]
Sorry for the late release, I've been very busy with high school graduation 😄
