### ISSUE TITLE
1.19.2 crashes after installing KFF

### ISSUE THREAD

**Issue by BartholomewIII** [thedarkcolour/KotlinForForge#75]
Trying to install cobblemon which requires KFF. Everytime I install any version of KFF the game crashes with exit code 2. It loads just fine without KFF installed but says that I need to install KFF for the cobblemon mod to work.

**Comment by thedarkcolour** [comment]
You're missing Architectury API.

**Comment by BartholomewIII** [comment]
This fixed it thanks.
