### ISSUE TITLE
[mod-compat] Risky class errors when paired with Essential mod

### ISSUE THREAD

**Issue by Cixon** [thedarkcolour/KotlinForForge#76]
1.20.1 - fml 47.1.3

Log (line 292)
[latest.log](https://github.com/thedarkcolour/KotlinForForge/files/12458664/latest.log)

Mod resource:
https://www.curseforge.com/minecraft/mc-mods/essential-mod/files/4717395

**Comment by thedarkcolour** [comment]
Essential is closed source and as such I cannot do anything on my end to fix the issue. Please report it to the Essential team.

**Comment by Cixon** [comment]
these event bus errors stretch a couple hundred of lines out, would love to see a fix to this.

**Comment by Cixon** [comment]
there isn't a issue tab anywhere. I'll just open a ticket in their discord I guess to relay the message. thanks anyway
