### ISSUE TITLE
Version dependencies seem unclear

### ISSUE THREAD

**Issue by ejektaflex** [thedarkcolour/KotlinForForge#78]
Hi! When including Kotlin for Forge via Maven, it's unclear which version of Kotlin and it's dependencies gets bundled in. It would be nice if this could be added to the changelogs on CurseForge or Modrinth, otherwise I'm not sure which to expect. 

Thanks! :)

**Comment by ejektaflex** [comment]
Even just version tags on the git commit timeline would make this easier, actually. I just can't seem to easily figure out which Kotlin versions are in which Kotlin For Forge release.

**Comment by thedarkcolour** [comment]
Ahh sorry about that. I'll make sure to do that from now on. 
Since I'm not home at the moment, you can check the gradle.properties file in the root of the Kotlin for Forge repository . It should have all of the dependency versions listed there.

**Comment by thedarkcolour** [comment]
I'm working on a [dependency spreadsheet](https://docs.google.com/spreadsheets/d/1v8K90PBa5qPFrlHBA8PSqlBTYCcp078o5E2XQbt5BUs/edit?usp=sharing) that should help clarify things in the future. It isn't done, but I'll be working on it for the next hour or so.
