### ISSUE TITLE
NeoForge support

### ISSUE THREAD

**Issue by FlorentTomi** [thedarkcolour/KotlinForForge#80]
Hello,
The NeoForged project just released their latest version, cutting down the cross-compatibility with Forge.
Are there any plan on supporting them?

Thank you!

**Comment by thedarkcolour** [comment]
Yes, I hope to have a version ready by the end of the week.

**Comment by thedarkcolour** [comment]
Looks like there are still a few issues in NeoForge that prevent language loaders from working. I can't say when KFF will support NeoForge, but for the meantime there seems to be no "minecraftLibrary" configuration in NeoGradle and NeoForge doesn't seem to detect the IModLanguageProvider service.

**Comment by FlorentTomi** [comment]
I assumed it was no easy task. They went crazy on the rewriting... 
I guess your issue with NeoGradle is a "bug": https://github.com/neoforged/NeoGradle/issues/12 .
Have you tried using their remapping script (https://gist.github.com/Technici4n/facbcdf18ce1a556b76e6027180c32ce)?
I see the mention of IModLanguageProvider in it, so I guess it must have changed in some ways.

I can't wait for your library to be compatible. I really can't stand Java and your good work has been a life saver.
If you need help from another software developer, I'm at your service ;).

**Comment by thedarkcolour** [comment]
Done. Kotlin for Forge 4.6.1 now supports NeoForge. Make sure you are using `kotlinforforge-neoforge` in your build.gradle and not `kotlinforforge` in your dependencies block.
