### ISSUE TITLE
Latest Update is Crashing on 1.20.1

### ISSUE THREAD

**Issue by Devilswarchild** [thedarkcolour/KotlinForForge#82]
forge 47.2.1
mod version: kotlinforforge-4.6.1-all.jar
mc 1.20.1

![image](https://github.com/thedarkcolour/KotlinForForge/assets/27385258/e455a121-be1c-400a-9f10-0fa475e6712b)

causing a crash during startup sequence

here is the crash log: 

[crash log](https://mclo.gs/CTp7Wlz)

[debug](https://mclo.gs/0pz0WD6)

[latest.log](https://mclo.gs/oJChJ4C)

**Comment by thedarkcolour** [comment]
Does it crash with 4.5.0?

**Comment by thedarkcolour** [comment]
Fixed in 4.6.2
