### ISSUE TITLE
registerObject is now broken in latest NeoForge version

### ISSUE THREAD

**Issue by RealYusufIsmail** [thedarkcolour/KotlinForForge#83]
This is because neo forge has changed the way you register an object which can be seen in the following pr

https://github.com/neoforged/NeoForge/pull/257

It now means As RegistryObject no longer exist

**Comment by RealYusufIsmail** [comment]
Issue currently with update to latest neo forge version in gradle, fix found by @thedarkcolour

**Comment by thedarkcolour** [comment]
Replaced with an extension function for DeferredHolder.getValue, which allows using the `by` syntax with any of the DeferredHolders returned by the DeferredRegister. Must use the following import: `import thedarkcolour.kotlinforforge.neoforge.forge.getValue`
