### ISSUE TITLE
KotlinForForge crash on startup on latest NeoForge

### ISSUE THREAD

**Issue by Prototik** [thedarkcolour/KotlinForForge#88]
Due to changes in FML in https://github.com/neoforged/FancyModLoader/commit/a43f00e9aaf2e2e08498fcbcf453fc28c90f1d1a
KFF crashes right on startup due to assignment to removed field here:
https://github.com/thedarkcolour/KotlinForForge/blob/2183403f3851cd6b564cb4c8761d8abde629744a/neoforge/kfflang/src/main/kotlin/thedarkcolour/kotlinforforge/neoforge/KotlinModContainer.kt#L41

**Comment by thedarkcolour** [comment]
I'll fix it today when I'm out of class

**Comment by thedarkcolour** [comment]
Fixed in 4.8.0
