### ISSUE TITLE
Crash in dev on NeoForge 20.4.40-beta (and later) due to changes in mods.toml

### ISSUE THREAD

**Issue by Prototik** [thedarkcolour/KotlinForForge#90]
In 20.4.40 NeoForge made changes in mods.toml format (see more [on their discord](https://discord.com/channels/313125603924639766/437004041394847745/1185682777245499412) or in [commit description](https://github.com/neoforged/NeoForge/commit/8786a13b2191ece3265e3c4de9517a7c2f572d3d)), and deprecated `mandatory` field in flavor of `type` field with `required`/`optional` values.
And made it hard failure in dev (dumbest thing I have ever seen, but who cares).

So KFF (which still uses `mandatory` field) no longer possible to use with latest Neo in Dev runtime, but in Prod it works just fine.

**Comment by thedarkcolour** [comment]
Fixed in 4.10.0
