### ISSUE TITLE
NeoForge renamed "mods.toml" to "neoforge.mods.toml", so the NeoForge version doesn't load anymore 

### ISSUE THREAD

**Issue by KP2048** [thedarkcolour/KotlinForForge#95]
When NeoForge updated to 1.20.5, they renamed the toml file from `mods.toml` to `neoforge.mods.toml`

**Comment by thedarkcolour** [comment]
I will keep this in mind when updating; more has changed too and many breaking changes will require KFF 5.x

**Comment by KP2048** [comment]
I suppose while it is a minor version technically speaking, most of the changes were done under the hood as opposed to gameplay mechanics. If there are enough changes to warrant a major version bump it would make total sense. If you would like help with it, I'm totally open to help. I primarily write my mods in Kotlin, and I use Architectury to share code between fabric/NeoForge, so you could say I'm invested in this project's success.

**Comment by thedarkcolour** [comment]
The breaking changes that affect Kotlin for Forge come from NeoForge, not Minecraft

**Comment by thedarkcolour** [comment]
I am working on fixing things right now.

**Comment by KP2048** [comment]
On a side note, being able to use expect/actual declarations with architectury would be a game changer, but afaik that only works with kotlin multiplatform projects and those don't separate platforms out into subprojects like Architectury does, it uses different source sets instead. I think a compiler plugin would potentially be necessary to make that work.

**Comment by KP2048** [comment]
> The breaking changes that affect Kotlin for Forge come from NeoForge, not Minecraft

While that is true, those changes probably stemmed from the changes to the game, also java 21 now

**Comment by thedarkcolour** [comment]
Nope. NeoForge just took this as an opportunity to do some cleanup and refactoring.

**Comment by KP2048** [comment]
Fair enough I guess.
