### ISSUE TITLE
kotlinx.serialization missing

### ISSUE THREAD

**Issue by trainb0y** [thedarkcolour/KotlinForForge#97]
For context, I was trying to port my mod from 1.20.2 to 1.20.6, and got to the point where it was crashing due to `java.lang.NoClassDefFoundError: kotlinx/serialization/KSerializer`.

In the past, I thought KotlinForForge bundled `kotlinx-serialization-core` and `kotlinx-serialization-json`, but it seems like 5.0 doesn't. Is this intentional?

![image](https://github.com/thedarkcolour/KotlinForForge/assets/66213737/650b9b44-9f04-46da-8ed8-3fbefcfd7744)

Also, sorry if this is just user error. I'm admittedly very new to (neo)forge modding.

**Comment by thedarkcolour** [comment]
Nope that's on me

**Comment by thedarkcolour** [comment]
Fixed in 5.0.2
